services:
  pg_jeeub:
    image: docker.io/postgres:15.1-alpine
    ports:
      - "55001:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DATABASE: postgres

  redis_jeeub:
    image: redis:7.0-alpine
    command: redis-server --requirepass jeeub
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master